### ISSUE TITLE
crash when splitting cursors

### ISSUE THREAD

**Issue by ianhattwick** [ijc8/cursors#18]
possible related to having multiple splits in the same column on adjacent rows

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 114, in _on_timer
    TimerBase._on_timer(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1187, in _on_timer
    ret = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/animation.py", line 1449, in _step
    still_going = Animation._step(self, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/animation.py", line 1169, in _step
    self._draw_next_frame(framedata, self._blit)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/animation.py", line 1188, in _draw_next_frame
    self._draw_frame(framedata)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/animation.py", line 1766, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "server.py", line 139, in update
    events = state.update(now - last)
  File "/Users/famle/CML/MLE/compositions/S20/Telematic/cursors/cursors.py", line 98, in update
    effector.function(self, cursor, pos)
  File "/Users/famle/CML/MLE/compositions/S20/Telematic/cursors/cursors.py", line 124, in split
    ind = state.cursors.index(cursor)
ValueError: Cursor(start=3, height=5, speed=3.0, pos=2.4222733974456787, merge_direction=-1) is not in list

**Comment by ianhattwick** [comment]
Able to reproduce with multiple split effeectors in the same column, even if they are not in adjacent rows
